import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1> DevOps Generated Project</h1>
        <div className="project-info">
          <h2>Project Details</h2>
          <p><strong>Repository:</strong> devops-generated-project-20260410_102945</p>
          <p><strong>Generated:</strong> 2026-04-10 10:29:45</p>
          <p><strong>Generator:</strong> DevOps Team Simulator</p>
        </div>
        
        <div className="features">
          <h3> Features Included</h3>
          <ul>
            <li> React 18 with TypeScript</li>
            <li> Vite for fast development</li>
            <li> Modern CSS styling</li>
            <li> Responsive design</li>
            <li> ESLint configuration</li>
            <li> Production ready build</li>
          </ul>
        </div>
        
        <div className="next-steps">
          <h3> Next Steps</h3>
          <ol>
            <li>Run <code>npm install</code> to install dependencies</li>
            <li>Run <code>npm run dev</code> to start development server</li>
            <li>Start building your amazing application!</li>
          </ol>
        </div>
        
        <footer>
          <p> Generated by DevOps Team Simulator</p>
          <p>Automated full-stack development at your fingertips!</p>
        </footer>
      </header>
    </div>
  );
}

export default App;
